name = 'Shahada Hugo Theme'
license = 'MIT'
licenselink = 'https://github.com/avicndugu/shahada-hugo-theme/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/avicndugu/shahada-hugo-theme/'

# If you have a running demo of the theme
demosite = 'https://shahada-hugo-theme.pages.dev/

# Taxonomy terms
tags = ['academic', 'portfolio']
features = ['projects', 'teaching', 'news']

# If the theme has a single author
[author]
  name = 'Avic Ndugu'
  homepage = 'https://avic.devpractical.com'

