baseURL = 'https://shahada-hugo-theme.pages.dev'
languageCode = 'en-us'
title = 'Shahada Hugo Theme'

theme='shahada-hugo-theme'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
